server:
  port: 8081
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.security: TRACE
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    open-in-view: false
  flyway:
    locations: classpath:db/migration,classpath:db/callback